server:
  port: 5000


spring:
 
  profiles:
    active: test
 
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:verizon_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
  
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
   
