server:
  port: 8000


spring:
 
#  profiles:
#    active: test
 
  datasource:
    url: jdbc:mysql://localhost:3306/verizon-docker-database
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
   
