server:
  port: 8081
  
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:product
    username: sa
    password: 
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    