server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
  
spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:h2:mem:cart
    username: sa
    password: 
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    