server:
  port: 8000


spring:
  datasource:
    url: jdbc:h2:mem:trainee_db
    username: sa
    password:
  h2:
    console.enabled: true
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
   
