server:
  port: 8081
  
spring:
  application:
    name: services-service
  datasource:
    url: jdbc:mysql://localhost:3306/services
    username: root
    password: 
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    